# This docker-compose file provides a pretty basic framework for testing the example
# application and tooling. It's a smoke test before release to make sure nothing
# _obviously_ broken gets out the door.
#
# It's designed to be run on my Linux machines, so it may have some Mac issues,
# but we'll sort them out as we go.

version: "3.2"
services:
  redis:
    image: "redis:3.2-alpine"
    expose:
      - 6379
    ports:
      - target: 6379
        published: 19981
        protocol: tcp
  producer:
    image: taskbotjs

